config/routes.rb
Rails.application.routes.draw do
  get 'booking/new'
  get "booking/new/:movie_id", to: "booking#sorttheater"
  get 'booking/new/:movie_id/:theater_id', to: 'booking#new'
  get 'shows/new'
  match '/create', to: 'shows#create', via: :post
  match '/show_timing', to: 'shows#show_timing', via: :post
  match '/book', to: 'booking#book', via: :post
  get '/bookings/index', to: "booking#index"
  get '/booking/:movie_id', to: 'booking#theater'
  resources :theaters
  get'/movies/:id/theaters', to: 'theaters#show'
  post '/theatre_booking_redirect/:movie_id/:theater_id', to: "theaters#booking_redirect"
  resources :movies

  devise_for :users
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  
  get 'home/index'
  root to: "home#index"

  resources :movies do
    member do
      delete :delete_file
    end
  end

  post '/movies' , to: "movies#new"
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_file
    file = ActiveStorage::Attachment.find(params[:id])
    file.purge
    redirect_back(fallback_location: movies_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:movie_name, :about_movie, :movie_format, :movie_duration, :movie_language, :header_image, :ticket_price)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :movie_name %>
    <%= form.text_field :movie_name %>
  </div>

  <div class="field">
    <%= form.label :about_movie %>
    <%= form.text_area :about_movie %>
  </div>

  <div class="field">
    <%= form.label :movie_format %>
    <%= form.text_field :movie_format %>
  </div>

  <div class="field">
    <%= form.label :movie_duration %>
    <%= form.text_field :movie_duration %>
  </div>

  <div class="field">
    <%= form.label :movie_language %>
    <%= form.text_field :movie_language %>
  </div>

   <div class="field">
   <%= form.label :header_image %>
   <%= form.file_field :header_image %>
 </div>

    <div class="field">
   <%= form.label :movie_price %>
   <%= form.text_field :ticket_price %>
 </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="all-movie">
    <% @movies.each do |movie| %>
      <div class="card" style="width: 18rem; margin-left: 5px; margin-top: 1%;" >
          <% if movie.header_image.attached?%>
          <%= image_tag movie.header_image,id:"movie-list"%>
          <% end %>
      <div class="card-body">
          <h5 class="card-title"><%= movie.movie_name %></h5>
          <p class="card-text"><%= movie.movie_format %></p>
          <p class="card-text"><%= movie.movie_duration %></p>
          <p class="card-text"><%= movie.movie_language %></p>
          <p class="card-text"><%= movie.ticket_price %></p>
          <button type="button" class="btn btn-outline-dark"><%= link_to 'show', movie %></button>
      </div>
  </div>
    <% end %>


<%# 
<%= link_to 'New Movie', new_movie_path %>
<%# <%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
  <% @movie.files.each do |file| %>
    <%= link_to file.filename, rails_blob_path(file, disposition: :attachment) %>
  <% end %>
      <p id="notice"><%= notice %></p>
        <p>
          <% if @movie.header_image.attached?%>
            <%= image_tag @movie.header_image,id:"movie-img"%>
          <% end %>
        </p>
          <div class="content-of-movies">
              <b><p id="movie-name"><%= @movie.movie_name %></p></b>
              <b><p id="movie-about"><%= @movie.about_movie %></p></b>
              <p><%= @movie.movie_format %></p>
              <p><%= @movie.movie_duration %></p>
              <p><%= @movie.movie_language %></p>
              <button type="button" class="btn btn-outline-dark"><%= link_to "theaters", "/movies/#{@movie.id}/theaters"%></button>
          </div>