config/routes.rb
Rails.application.routes.draw do
  get 'booking/new'
  get "booking/new/:movie_id", to: "booking#sorttheater"
  get 'booking/new/:movie_id/:theater_id', to: 'booking#new'
  get 'shows/new'
  match '/create', to: 'shows#create', via: :post
  match '/show_timing', to: 'shows#show_timing', via: :post
  match '/book', to: 'booking#book', via: :post
  get '/bookings/index', to: "booking#index"
  get '/booking/:movie_id', to: 'booking#theater'
  resources :theaters
  get'/movies/:id/theaters', to: 'theaters#show'
  post '/theatre_booking_redirect/:movie_id/:theater_id', to: "theaters#booking_redirect"
  resources :movies

  devise_for :users
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  
  get 'home/index'
  root to: "home#index"

  resources :movies do
    member do
      delete :delete_file
    end
  end

  post '/movies' , to: "movies#new"
end

app/models/theater.rb
class Theater < ApplicationRecord
    has_many :shows
    has_many :show_timings
    has_many :bookings
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  before_action :set_theater, only: %i[ show edit update destroy ]

  # GET /theaters or /theaters.json
  def index
    @theaters = Theater.all
  end

  # GET /theaters/1 or /theaters/1.json
  def show
    # @theaters = Theater.joins("inner join shows on theaters.id = shows.theater_id and movie_id = #{params[:id]}")
    @theaters = []
    Movie.find(params[:id]).shows.all.each do |show|
      @theaters.push(show.theater)
    end
    @theaters
  end

  # GET /theaters/new
  def new
    @theater = Theater.new
  end

  # GET /theaters/1/edit
  def edit
  end

  # POST /theaters or /theaters.json
  def create
    @theater = Theater.new(theater_params)

    respond_to do |format|
      if @theater.save
        format.html { redirect_to theater_url(@theater), notice: "Theater was successfully created." }
        format.json { render :show, status: :created, location: @theater }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theaters/1 or /theaters/1.json
  def update
    respond_to do |format|
      if @theater.update(theater_params)
        format.html { redirect_to theater_url(@theater), notice: "Theater was successfully updated." }
        format.json { render :show, status: :ok, location: @theater }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theaters/1 or /theaters/1.json
  def destroy
    @theater.destroy

    respond_to do |format|
      format.html { redirect_to theaters_url, notice: "Theater was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  ##Redirecting to booking page
  def booking_redirect
    @movie_id = params[:movie_id]
    @theater_id = params[:theater_id]
    redirect_to "/booking/new/#{@movie_id}/#{@theater_id}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theater
      # @theater = Theater.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theater_params
      params.require(:theater).permit(:theater_name, :theater_location)
    end
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/theaters/_form.html.erb
<%= form_with(model: theater) do |form| %>
  <% if theater.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theater.errors.count, "error") %> prohibited this theater from being saved:</h2>

      <ul>
        <% theater.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :theater_name %>
    <%= form.text_field :theater_name %>
  </div>

  <div class="field">
    <%= form.label :theater_location %>
    <%= form.text_area :theater_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/theaters/edit.html.erb
<h1>Editing Theater</h1>

<%= render 'form', theater: @theater %>

<%= link_to 'Show', @theater %> |
<%= link_to 'Back', theaters_path %>

app/views/theaters/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Theaters</h1>

    <table>
      <tbody>
        <% @theaters.each do |theater| %>
          <div class="card">
            <h5 class="card-header">Theater name:</h5>
              <div class="card-body">
                  <h4 class="card-title"><%= theater.theater_name %></h4>
                  <p class="card-title">Theater location:</p>
                  <p class="card-text"><%= theater.theater_location %></p>
                  <button type="button" class="btn btn-outline-dark"><%= link_to 'Book', "/booking/new/0/#{theater.id}" %></button>
              </div>
          </div>
        <% end %>
      </tbody>
    </table>

app/views/theaters/new.html.erb
<h1>New Theater</h1>

<%= render 'form', theater: @theater %>

<%= link_to 'Back', theaters_path %>

app/views/theaters/show.html.erb
<%= image_tag('Theater.png',alt: "",class:"rounded mx-auto d-block") %>
<p id="notice"><%= notice %></p>

    <% @theaters.each do |theater| %>
        <div class="card">
          <h5 class="card-header">Theater name:</h5>
            <div class="card-body">
              <h4 class="card-title"><%= theater.theater_name %></h4>
              <p class="card-title">Theater location:</p>
              <p class="card-text"><%= theater.theater_location %></p>
                <form action="/theatre_booking_redirect/<%=params[:id]%>/<%=theater.id%>" method="post">
                  <button type="submit" class="btn btn-outline-dark"> Book </button> 
                  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                </form>
        </div>
    <% end %>